## DATABASE PROPERTIES
spring.datasource.url=jdbc:mysql://localhost:3306/taskscheduler
spring.datasource.username=taskscheduler_user
spring.datasource.password=passtaskscheduler
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



